//! Frequency estimation algorithms

mod conservative_count_min;
mod count_min;
mod count_sketch;
mod cuckoo_heavy_keeper;
pub mod elastic_sketch;
mod fcm_sketch;
pub mod frequent;
mod heavy_keeper;
mod mv_sketch;
mod nitrosketch;
mod on_off_sketch;
pub mod removable_sketch;
mod rhhh;
pub mod salsa;
mod space_saving;
mod space_saving_pm;
mod spread_sketch;
mod tower_sketch;
mod unbiased_space_saving;
mod waving_sketch;

pub use conservative_count_min::ConservativeCountMin;
pub use count_min::CountMinSketch;
pub use count_sketch::CountSketch;
pub use cuckoo_heavy_keeper::CuckooHeavyKeeper;
pub use elastic_sketch::ElasticSketch;
pub use fcm_sketch::FcmSketch;
pub use frequent::{ErrorType, FrequentItems};
pub use heavy_keeper::HeavyKeeper;
pub use mv_sketch::MvSketch;
pub use nitrosketch::{NitroSketch, NitroSketchStats};
pub use on_off_sketch::OnOffSketch;
pub use removable_sketch::RemovableUniversalSketch;
pub use rhhh::Rhhh;
pub use salsa::SALSA;
pub use space_saving::SpaceSaving;
pub use space_saving_pm::SpaceSavingPlusMinus;
pub use spread_sketch::SpreadSketch;
pub use tower_sketch::TowerSketch;
pub use unbiased_space_saving::UnbiasedSpaceSaving;
pub use waving_sketch::WavingSketch;
