//! Frequency estimation algorithms

mod bubble_sketch;
mod conservative_count_min;
mod count_min;
mod count_min_log;
mod count_sketch;
mod cuckoo_heavy_keeper;
pub mod elastic_sketch;
mod fcm_sketch;
mod filtered_space_saving;
pub mod frequent;
mod frequent_distinct_tuples;
mod heavy_keeper;
mod heavy_locker;
mod hidden_sketch;
mod lossy_counting;
mod mv_sketch;
mod nitrosketch;
mod on_off_sketch;
pub mod removable_sketch;
mod rhhh;
pub mod salsa;
mod space_saving;
mod space_saving_pm;
mod spread_sketch;
mod stable_sketch;
mod sticky_sampling;
mod tower_sketch;
mod unbiased_space_saving;
mod waving_sketch;

pub use bubble_sketch::BubbleSketch;
pub use conservative_count_min::ConservativeCountMin;
pub use count_min::CountMinSketch;
pub use count_min_log::CountMinLog;
pub use count_sketch::CountSketch;
pub use cuckoo_heavy_keeper::CuckooHeavyKeeper;
pub use elastic_sketch::ElasticSketch;
pub use fcm_sketch::FcmSketch;
pub use filtered_space_saving::FilteredSpaceSaving;
pub use frequent::{ErrorType, FrequentItems};
pub use frequent_distinct_tuples::FrequentDistinctTuples;
pub use heavy_keeper::HeavyKeeper;
pub use heavy_locker::HeavyLocker;
pub use hidden_sketch::HiddenSketch;
pub use lossy_counting::LossyCounting;
pub use mv_sketch::MvSketch;
pub use nitrosketch::{NitroSketch, NitroSketchStats};
pub use on_off_sketch::OnOffSketch;
pub use removable_sketch::RemovableUniversalSketch;
pub use rhhh::Rhhh;
pub use salsa::SALSA;
pub use space_saving::SpaceSaving;
pub use space_saving_pm::SpaceSavingPlusMinus;
pub use spread_sketch::SpreadSketch;
pub use stable_sketch::StableSketch;
pub use sticky_sampling::StickySampling;
pub use tower_sketch::TowerSketch;
pub use unbiased_space_saving::UnbiasedSpaceSaving;
pub use waving_sketch::WavingSketch;
