/* tslint:disable */
/* eslint-disable */
/* prettier-ignore */

/* auto-generated by NAPI-RS */

const { existsSync, readFileSync } = require('fs')
const { join } = require('path')

const { platform, arch } = process

let nativeBinding = null
let localFileExisted = false
let loadError = null

function isMusl() {
  // For Node 10
  if (!process.report || typeof process.report.getReport !== 'function') {
    try {
      const lddPath = require('child_process').execSync('which ldd').toString().trim()
      return readFileSync(lddPath, 'utf8').includes('musl')
    } catch (e) {
      return true
    }
  } else {
    const { glibcVersionRuntime } = process.report.getReport().header
    return !glibcVersionRuntime
  }
}

switch (platform) {
  case 'android':
    switch (arch) {
      case 'arm64':
        localFileExisted = existsSync(join(__dirname, 'sketch_oxide_node.android-arm64.node'))
        try {
          if (localFileExisted) {
            nativeBinding = require('./sketch_oxide_node.android-arm64.node')
          } else {
            nativeBinding = require('sketch-oxide-node-android-arm64')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'arm':
        localFileExisted = existsSync(join(__dirname, 'sketch_oxide_node.android-arm-eabi.node'))
        try {
          if (localFileExisted) {
            nativeBinding = require('./sketch_oxide_node.android-arm-eabi.node')
          } else {
            nativeBinding = require('sketch-oxide-node-android-arm-eabi')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on Android ${arch}`)
    }
    break
  case 'win32':
    switch (arch) {
      case 'x64':
        localFileExisted = existsSync(
          join(__dirname, 'sketch_oxide_node.win32-x64-msvc.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./sketch_oxide_node.win32-x64-msvc.node')
          } else {
            nativeBinding = require('sketch-oxide-node-win32-x64-msvc')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'ia32':
        localFileExisted = existsSync(
          join(__dirname, 'sketch_oxide_node.win32-ia32-msvc.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./sketch_oxide_node.win32-ia32-msvc.node')
          } else {
            nativeBinding = require('sketch-oxide-node-win32-ia32-msvc')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'arm64':
        localFileExisted = existsSync(
          join(__dirname, 'sketch_oxide_node.win32-arm64-msvc.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./sketch_oxide_node.win32-arm64-msvc.node')
          } else {
            nativeBinding = require('sketch-oxide-node-win32-arm64-msvc')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on Windows: ${arch}`)
    }
    break
  case 'darwin':
    localFileExisted = existsSync(join(__dirname, 'sketch_oxide_node.darwin-universal.node'))
    try {
      if (localFileExisted) {
        nativeBinding = require('./sketch_oxide_node.darwin-universal.node')
      } else {
        nativeBinding = require('sketch-oxide-node-darwin-universal')
      }
      break
    } catch {}
    switch (arch) {
      case 'x64':
        localFileExisted = existsSync(join(__dirname, 'sketch_oxide_node.darwin-x64.node'))
        try {
          if (localFileExisted) {
            nativeBinding = require('./sketch_oxide_node.darwin-x64.node')
          } else {
            nativeBinding = require('sketch-oxide-node-darwin-x64')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'arm64':
        localFileExisted = existsSync(
          join(__dirname, 'sketch_oxide_node.darwin-arm64.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./sketch_oxide_node.darwin-arm64.node')
          } else {
            nativeBinding = require('sketch-oxide-node-darwin-arm64')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on macOS: ${arch}`)
    }
    break
  case 'freebsd':
    if (arch !== 'x64') {
      throw new Error(`Unsupported architecture on FreeBSD: ${arch}`)
    }
    localFileExisted = existsSync(join(__dirname, 'sketch_oxide_node.freebsd-x64.node'))
    try {
      if (localFileExisted) {
        nativeBinding = require('./sketch_oxide_node.freebsd-x64.node')
      } else {
        nativeBinding = require('sketch-oxide-node-freebsd-x64')
      }
    } catch (e) {
      loadError = e
    }
    break
  case 'linux':
    switch (arch) {
      case 'x64':
        if (isMusl()) {
          localFileExisted = existsSync(
            join(__dirname, 'sketch_oxide_node.linux-x64-musl.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./sketch_oxide_node.linux-x64-musl.node')
            } else {
              nativeBinding = require('sketch-oxide-node-linux-x64-musl')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(
            join(__dirname, 'sketch_oxide_node.linux-x64-gnu.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./sketch_oxide_node.linux-x64-gnu.node')
            } else {
              nativeBinding = require('sketch-oxide-node-linux-x64-gnu')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 'arm64':
        if (isMusl()) {
          localFileExisted = existsSync(
            join(__dirname, 'sketch_oxide_node.linux-arm64-musl.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./sketch_oxide_node.linux-arm64-musl.node')
            } else {
              nativeBinding = require('sketch-oxide-node-linux-arm64-musl')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(
            join(__dirname, 'sketch_oxide_node.linux-arm64-gnu.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./sketch_oxide_node.linux-arm64-gnu.node')
            } else {
              nativeBinding = require('sketch-oxide-node-linux-arm64-gnu')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 'arm':
        if (isMusl()) {
          localFileExisted = existsSync(
            join(__dirname, 'sketch_oxide_node.linux-arm-musleabihf.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./sketch_oxide_node.linux-arm-musleabihf.node')
            } else {
              nativeBinding = require('sketch-oxide-node-linux-arm-musleabihf')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(
            join(__dirname, 'sketch_oxide_node.linux-arm-gnueabihf.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./sketch_oxide_node.linux-arm-gnueabihf.node')
            } else {
              nativeBinding = require('sketch-oxide-node-linux-arm-gnueabihf')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 'riscv64':
        if (isMusl()) {
          localFileExisted = existsSync(
            join(__dirname, 'sketch_oxide_node.linux-riscv64-musl.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./sketch_oxide_node.linux-riscv64-musl.node')
            } else {
              nativeBinding = require('sketch-oxide-node-linux-riscv64-musl')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(
            join(__dirname, 'sketch_oxide_node.linux-riscv64-gnu.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./sketch_oxide_node.linux-riscv64-gnu.node')
            } else {
              nativeBinding = require('sketch-oxide-node-linux-riscv64-gnu')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 's390x':
        localFileExisted = existsSync(
          join(__dirname, 'sketch_oxide_node.linux-s390x-gnu.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./sketch_oxide_node.linux-s390x-gnu.node')
          } else {
            nativeBinding = require('sketch-oxide-node-linux-s390x-gnu')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on Linux: ${arch}`)
    }
    break
  default:
    throw new Error(`Unsupported OS: ${platform}, architecture: ${arch}`)
}

if (!nativeBinding) {
  if (loadError) {
    throw loadError
  }
  throw new Error(`Failed to load native binding`)
}

const { HyperLogLog, UltraLogLog, CpcSketch, QSketch, ThetaSketch, CountMinSketch, CountSketch, ConservativeCountMin, SpaceSaving, FrequentItemsErrorType, FrequentItems, BinaryFuseFilter, BloomFilter, BlockedBloomFilter, CountingBloomFilter, CuckooFilter, RibbonFilter, StableBloomFilter, DdSketch, ReqSketchMode, ReqSketch, TDigest, KllSketch, SplineSketch, MinHash, SimHash, ReservoirSampling, VarOptSampling, SlidingWindowCounter, ExponentialHistogram, ElasticSketch, Salsa, RemovableUniversalSketch, HeavyKeeper, RatelessIblt, Grafite, MementoFilter, SlidingHyperLogLog, VacuumFilter, Grf, NitroSketch, UnivMon, LearnedBloomFilter } = nativeBinding

module.exports.HyperLogLog = HyperLogLog
module.exports.UltraLogLog = UltraLogLog
module.exports.CpcSketch = CpcSketch
module.exports.QSketch = QSketch
module.exports.ThetaSketch = ThetaSketch
module.exports.CountMinSketch = CountMinSketch
module.exports.CountSketch = CountSketch
module.exports.ConservativeCountMin = ConservativeCountMin
module.exports.SpaceSaving = SpaceSaving
module.exports.FrequentItemsErrorType = FrequentItemsErrorType
module.exports.FrequentItems = FrequentItems
module.exports.BinaryFuseFilter = BinaryFuseFilter
module.exports.BloomFilter = BloomFilter
module.exports.BlockedBloomFilter = BlockedBloomFilter
module.exports.CountingBloomFilter = CountingBloomFilter
module.exports.CuckooFilter = CuckooFilter
module.exports.RibbonFilter = RibbonFilter
module.exports.StableBloomFilter = StableBloomFilter
module.exports.DdSketch = DdSketch
module.exports.ReqSketchMode = ReqSketchMode
module.exports.ReqSketch = ReqSketch
module.exports.TDigest = TDigest
module.exports.KllSketch = KllSketch
module.exports.SplineSketch = SplineSketch
module.exports.MinHash = MinHash
module.exports.SimHash = SimHash
module.exports.ReservoirSampling = ReservoirSampling
module.exports.VarOptSampling = VarOptSampling
module.exports.SlidingWindowCounter = SlidingWindowCounter
module.exports.ExponentialHistogram = ExponentialHistogram
module.exports.ElasticSketch = ElasticSketch
module.exports.Salsa = Salsa
module.exports.RemovableUniversalSketch = RemovableUniversalSketch
module.exports.HeavyKeeper = HeavyKeeper
module.exports.RatelessIblt = RatelessIblt
module.exports.Grafite = Grafite
module.exports.MementoFilter = MementoFilter
module.exports.SlidingHyperLogLog = SlidingHyperLogLog
module.exports.VacuumFilter = VacuumFilter
module.exports.Grf = Grf
module.exports.NitroSketch = NitroSketch
module.exports.UnivMon = UnivMon
module.exports.LearnedBloomFilter = LearnedBloomFilter
